general {
	hide_cursor = true
	ignore_empty_input = true
}

animations {
	enabled = true
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/.local/share/wallpapers/tux.png
    blur_passes = 1
	blur_size = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 1
    inner_color = rgba(0, 0, 0, 0.3)

    outer_color = rgb(255, 255, 255)
	check_color = rgb(204, 136, 34)
    fail_color = rgb(255, 0, 0)

    font_color = rgb(255, 255, 255)
    fade_on_empty = false
	placeholder_text = Hi there, $USER
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:30000] ~/.config/hypr/hyprlock-battery.sh
    color = rgb(255, 255, 255)
    font_size = 16
    font_family = Noto Sans

    position = -10, -10
    halign = right
    valign = top
}

label {
    monitor =
    text = $TIME
    color = rgb(255, 255, 255)
    font_size = 100
    font_family = Noto Sans

    position = 0, 100
    halign = center
    valign = center
}
